package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"strings"

	"github.com/metaleap/go-util-fs"
)

/*
Representation of a PureScript module from which a
Golang package will be generated. Hence 'modpkg'..

Holds intermediate representations in girMeta and girAst.
*/

type ModuleInfo struct {
	reGenGIr        bool
	qName           string //	eg	Control.Monad.Eff.Uncurried, My.Main etc
	lName           string //	eg	Uncurried, Main etc
	pName           string //	eg	Control_Monad_Eff_Uncurried, My_Main etc
	srcFilePath     string //	eg	bower_components/purescript-eff/src/Control/Monad/Eff/Uncurried.purs or src/My/Main.purs etc
	impFilePath     string //	eg	output/Control.Monad.Eff.Uncurried/coreimp.json, output/My.Main/coreimp.json etc
	extFilePath     string //	eg	output/Control.Monad.Eff.Uncurried/externs.json, output/My.Main/externs.json etc
	girMetaFilePath string //	eg	output/Control.Monad.Eff.Uncurried/gonadmeta.json, output/My.Main/gonadmeta.json etc
	girAstFilePath  string //	eg	output/Control.Monad.Eff.Uncurried/gonadast.json, output/My.Main/gonadast.json etc
	goOutDirPath    string //	eg	Control/Monad/Eff/Uncurried, My/Main etc
	goOutFilePath   string //	eg	Control/Monad/Eff/Uncurried/Uncurried.go, My/Main/Main.go etc

	girMeta       *GonadIrMeta
	girAst        *GonadIrAst
	proj          *PsBowerProject // parent
	gopkgfilepath string          // full target file path (not necessarily absolute but starting with the given gopath)
	ext           *PsExt
	coreimp       *CoreImp
}

var (
	slash2dot      = strings.NewReplacer("\\", ".", "/", ".")
	dot2slash      = strings.NewReplacer(".", "/")
	dot2underscore = strings.NewReplacer(".", "_")
)

func FindModuleByQName(qname string) (modinfo *ModuleInfo) {
	if modinfo = Proj.ModuleByQName(qname); modinfo == nil {
		for _, dep := range Deps {
			if modinfo = dep.ModuleByQName(qname); modinfo != nil {
				return
			}
		}
	}
	return
}

func FindModuleByPName(pname string) (modinfo *ModuleInfo) {
	if modinfo = Proj.ModuleByPName(pname); modinfo == nil {
		for _, dep := range Deps {
			if modinfo = dep.ModuleByPName(pname); modinfo != nil {
				return
			}
		}
	}
	return
}

func (me *ModuleInfo) loadPkgGIrMeta() (err error) {
	var jsonbytes []byte
	if jsonbytes, err = ioutil.ReadFile(me.girMetaFilePath); err == nil {
		if err = json.Unmarshal(jsonbytes, &me.girMeta); err == nil {
			err = me.girMeta.PopulateFromLoaded()
		}
	}
	return
}

func (me *ModuleInfo) reGenPkgGIrMeta() (err error) {
	var jsonbytes []byte
	if jsonbytes, err = ioutil.ReadFile(me.extFilePath); err == nil {
		if err = json.Unmarshal(jsonbytes, &me.ext); err == nil {
			me.ext.modinfo = me
			if jsonbytes, err = ioutil.ReadFile(me.impFilePath); err == nil {
				if err = json.Unmarshal(jsonbytes, &me.coreimp); err == nil {
					me.coreimp.mod = me
					girmeta := GonadIrMeta{save: true, mod: me, proj: me.proj}
					girmeta.PopulateFromCoreImp()
					me.girMeta = &girmeta
				}
			}
		}
	}
	return
}

func (me *ModuleInfo) prepGIrAst() (err error) {
	if err = me.coreimp.preProcessTopLevel(); err == nil {
		me.girAst = &GonadIrAst{mod: me, proj: me.proj, girM: me.girMeta}
		err = me.girAst.PrepFromCoreImp()
	}
	return
}

func (me *ModuleInfo) reGenPkgGIrAst() (err error) {
	if err = me.girAst.FinalizePostPrep(); err == nil {
		var buf bytes.Buffer
		if err = me.girAst.WriteAsJsonTo(&buf); err == nil {
			if err = ufs.WriteBinaryFile(me.girAstFilePath, buf.Bytes()); err == nil {
				buf.Reset()
				if !Flag.NoPrefix {
					fmt.Fprintf(&buf, "// Generated by gonad from: %s, generated from: %s\n", me.impFilePath, me.srcFilePath)
				}
				if err = me.girAst.WriteAsGoTo(&buf); err == nil {
					err = ufs.WriteBinaryFile(me.gopkgfilepath, buf.Bytes())
				}
			}
		}
	}
	return
}
